### ISSUE TITLE
Provides a way to build web component as distributable library

### ISSUE THREAD

**Issue by softdays** [open-wc/open-wc#1186] opened 2020-01-02 11:15 UTC
I don't know if it could be a feature request or a question, but anyway...

At the moment, the different build options (rollup+webpack) provide us the capacity to build an app or a demo because the build tools takes the `index.html` file as entry point. But here is another common use case for developers which just consists into build a component as a distributable library (production-ready) that they could then deploy to a NPM registry.

It seems that this UC is not covered but maybe I missed something?

**Comment by LarsDenBakker** [comment] 2020-01-02 21:19
This is an area we intend to cover very soon.

In general es modules + code that runs in modern browsers is what you want to publish for libraries and web components. If you are using non standard code like typescript, you will need to compile that away, but there is no need to do any es5 or bunding. All modern browsers support es modules, classes, async functions etc. Your consumers know best how to optimize for their users.

https://justinfagnani.com/2019/11/01/how-to-publish-web-components-to-npm/ is a good read and covers mostly our point of view.

**Comment by softdays** [comment] 2020-01-03 09:44
Many thanks for your answer.

**Comment by softdays** [comment] 2020-01-03 10:05
If someone has to work in that direction, here is a rollup config which can help you to start with:
```javascript
import resolve from '@rollup/plugin-node-resolve';
import typescript from 'rollup-plugin-typescript';

export default {
    input: ['src/mycomp.js'],
    output: {
        file: 'dist/mycomp.js',
        format: 'esm',
        sourcemap: true
    },
    plugins: [
        resolve(), 
        typescript({ lib: ["es2018", "dom"], target: "es2017", include: '**/*.{ts,js}' })
    ]
};
```

**Comment by Alos** [comment] 2020-08-06 21:13
So to clarify, the open-wc startup skeleton app does not have a way to build a "publishable" web component and we need to add this on our own?

**Comment by LarsDenBakker** [comment] 2020-08-07 05:23
We actually got around to writing these docs now: https://open-wc.org/publishing/

We recommend people to write and publish standard JS, thus there is no build tools needed for the web component generator. If you use typescript you need to compile away the types, if you pick the typescript the tools for that are included.

I'll close this since the original issue was solved, but feel free to create a new issue with a followup question.

**Comment by Alos** [comment] 2020-08-07 17:14
Right, the issue is that by default, the open-wc skeleton is not configured to follow the rules outlined. I've created another issue to track that: #1797 

Let me know if I'm doing something wrong.

**Comment by LarsDenBakker** [comment] 2020-08-08 08:13
Thanks. Will close this one and track the other issue in the new one.

**Closed by LarsDenBakker** 2020-08-08 08:13 UTC
Labels: docs, enhancement
