### ISSUE TITLE
Upgrade an existing project option fails

### ISSUE THREAD

**Issue by Pickra** [open-wc/open-wc#2488] opened 2022-08-16 22:17 UTC
## Expected behavior
- Have an existing project, generated by `npm init @open-wc`
- Run the command again, `npm init @open-wc`, and something happens

I'm honestly not sure what the expected behavior is, not seeing that documentation. I assumed it would upgrade the project and or generate a new component.

## Actual Behavior
It fails.
<img width="1792" alt="Screen Shot 2022-08-16 at 6 15 46 PM" src="https://user-images.githubusercontent.com/5226549/184994740-1246b514-17ef-43df-aa78-1b421818bdea.png">

## Additional context
[Test Repo](https://github.com/Pickra/open-wc)

OS: Mac
node : v14.17.0
npm : 6.14.13

"@custom-elements-manifest/analyzer": "^0.4.17",
"@open-wc/scoped-elements": "2.1.2",
"@open-wc/testing": "3.1.6",
"@web/dev-server": "^0.1.28",
"@web/dev-server-storybook": "0.5.1",
"@web/test-runner": "next",
"concurrently": "^5.3.0",
"lit": "2.2.7"
"lit-html": "2.2.6",
"tslib": "^2.3.1",
"typescript": "^4.5.2"

Thank you for your time.

**Comment by web-padawan** [comment] 2022-11-18 17:46
Duplicate of https://github.com/open-wc/create/issues/58. Closing.

**Closed by web-padawan** 2022-11-18 17:46 UTC
