### ISSUE TITLE
Built-in modules and node-resolve

### ISSUE THREAD

**Issue by gpista** [open-wc/open-wc#1534] opened 2020-04-18 20:33 UTC
I've been trying to add the `uuid` module to an app I'm building using `open-wc` and kept running into errors with `node-resolve`. I was finally able to solve it but I'd like to share what I did because it was way more difficult than I hoped. I'm curious if I'm just missing something and there is a simpler way, or maybe this could be improved either by adding these steps to the docs or changing the default `node-resolve` options in `open-wc`.

The issue can be recreated by starting with a brand-new application using `npm init @open-wc`, installing the `uuid` npm package and importing and calling it somewhere in the main app js file.
If I try to run the app with `npm run start` I get the following errors:
```
Error compiling: Could not resolve import "crypto" in "./node_modules/uuid/dist/esm-node/rng.js".

Error compiling: Could not resolve import "crypto" in "./node_modules/uuid/dist/esm-node/md5.js".

Error compiling: Could not resolve import "crypto" in "./node_modules/uuid/dist/esm-node/sha1.js".
```
If I try to create a production build with `npm run build`, the build finishes, but I see the following in the output:
```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
crypto (imported by node_modules/uuid/dist/esm-node/rng.js, node_modules/uuid/dist/esm-node/md5.js, node_modules/uuid/dist/esm-node/sha1.js)
```
If I then run the build with `npm run start:build` the browser loads with a blank page with the following error in the developer console (on chrome):
```
Uncaught TypeError: Failed to resolve module specifier "crypto". Relative references must start with either "/", "./", or "../".
```
After some googling and lots of trial and error I found that the key to solve the problem is adding `browser: true` to the `node-resolve` rollup plugin config, but doing this is not that straightforward.

For the build case, I can see that in the newest version of open-wc I can add `nodeResolve: { browser: true }` to the config object that's passed to `createSpaConfig` (or `createBasicConfig`) in `rollup.config.js`. When I created another test app just a week ago, `rollup.config.js` still had `createDefaultConfig` which didn't allow you to pass options to the `node-resolve` plugin, so I had to manually edit `node_modules/@open-wc/building-rollup/modern-config.js` to make it work.
So if anyone else runs into this issue with an older version of `open-wc`, you can solve it by recreating your app with the latest version and adding `nodeResolve: { browser: true }` to `rollup.config.js`.

For the development case (using `npm run start`), I had to create an `es-dev-server.config.js` file in my project that contained `module.exports = { nodeResolve: { browser: true } };`
This is documented on https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server, so that's fair I guess. What wasn't obvious at first is that you also have to edit your `package.json` and remove the `--node-resolve` flag from the `start` script definition, otherwise it overrides the value of `nodeResolve` in the config to a simple boolean `true` instead of the object you defined in `es-dev-server.config.js`. I guess this behavior makes sense, but it would help if the docs would mention it explicitly.

I only ran into this problem when trying to use `uuid`, which uses `crypto`, but you would have the same problem trying to use any other built-in module. Since this is not an especially rare use-case, I think it should either just work out of the box, or the steps to make it work should be clearly included in the docs. Since the apps built with `open-wc` always run in the browser, I think the `browser: true` option should just be included by default for both the build and dev use-case, unless this would cause some other issues that I'm not aware of.

For the build case it could be either added to the generated `rollup.config.js` by default, or added to `packages/building-rollup/src/createBasicConfig.js`. I think the latter makes more sense.
For the dev case, the init project should either include a default `es-dev-server.config.js` with the options added (and the '--node-resolve' option removed from the `start` script definition in `package.json`), or the option should be included in `es-dev-server` by default. In the latter case it should probably be added to `packages/es-dev-server/src/config.js`.

If you agree that it's a good idea to include `browser: true` in the default `node-resolve` configs, I'd be happy to submit a pull request.

**Comment by LarsDenBakker** [comment] 2020-04-19 15:04
Hi there! Thanks for the lengthy description.

Indeed we made it easier to modify plugin configs in building-rollup v1 for this reason.

The `--node-resolve` flag overriding the value in the config is by design, CLI flags take priority over the config values so that you can reuse the same config across multiple commands. node-resolve also takes a boolean, so it would use "true" when used from the CLI and take the default config.

In es-dev-server we do specify the `preferBuiltins` option, I thought that was enough for resolving built-in node modules. I'm fine with adding browser by default in rollup and EDS, but I thought it was deprecated on the side of the node resolve plugin because there are more modern alternatives. Doesn't hurt to add it though.

If you want to submit a PR for this, that would be great.

**Comment by aronerben** [comment] 2020-08-17 09:24
This was really helpful, thanks @gpista!

**Comment by LarsDenBakker** [comment] 2020-11-02 07:57
We tried using browser by default, but this broke for a lot of other packages because it was pointing to commonjs packages instead of the es module packages. es-dev-server is now replaced by `@web-dev-server` where you can configure the options for the rollup node resolve plugin by setting it to an object: https://modern-web.dev/docs/dev-server/cli-and-configuration/#configuration-file

**Closed by LarsDenBakker** 2020-11-02 07:57 UTC
Labels: enhancement, good first issue, help wanted
