### ISSUE TITLE
[es-dev-server] stale files after git checkout

### ISSUE THREAD

**Issue by cristinecula** [open-wc/open-wc#930] opened 2019-11-01 08:08 UTC
I have started using `es-dev-server` to work on a large project (1000+ modules) and I really like the fact that it sets proper cache headers. This feature dropped the development loading time from 10s to 1.5s (I was using `polymer serve`).

Unfortunately, I ran into a problem: the server sends stale responses after switching branches. This is the scenario:

1. checkout master
2. start es-dev-server
3. edit a file
4. confirm that latest version is served
5. checkout feature branch
6. confirm that feature branch code is served
7. edit the same file
8. notice that the feature branch version is still served, instead of the edited code

if 8 did not happen, then checkout master again and notice that the code from 7. is still served.

This staleness does not go away until I restart the server, no matter how many times I edit and save the file.

This is not a browser cache problem, as I have tested this with disabled cache (via network panel). 

My hunch is that it's somehow related to the filesystem change event, but I have yet to look in the es-dev-server internals.

P.S. Thank you for this awesome project! 
<3

**Comment by LarsDenBakker** [comment] 2019-11-01 09:12
Fast startup of large unbundled project is definitely one of the primary design goals of es-dev-server :)

One thing we do is keep an in-memory cache in the server, this is especially useful if you do any kind of babel or compatibility transformation. 

This cache is busted whenever a file is changed, using `chokidar` to watch files. https://github.com/open-wc/open-wc/blob/master/packages/es-dev-server/src/middleware/response-cache-middleware.js#L48

I assume this event would be fired when using git checkout?

**Comment by cristinecula** [comment] 2019-11-01 09:42
I assume so... 
Immediately after git checkout, es-dev-server serves the correct files, but (sometimes) changes made after that are not served.

**Comment by LarsDenBakker** [comment] 2019-11-01 09:43
Ah, right. And you've only seen this happen after a git checkout?

**Comment by cristinecula** [comment] 2019-11-01 09:45
Well... I was able to reproduce it fairly reliably using git checkout, but I can't confirm if this is the only scenario that triggers the bug.

It might be related to https://github.com/paulmillr/chokidar/issues/917.

**Comment by LarsDenBakker** [comment] 2019-11-02 13:56
I'm not able to reproduce this locally with a git checking right now, might be OS related too. 

Relying on chokidar like this might be a bit too dangerous, I'm going to look into how bad it would be to do a file system check for changes each serve. Then we let the file system be the source of truth.

**Comment by LarsDenBakker** [comment] 2019-11-02 16:03
Turns out `fs.stat` is just 0-2ms so I'll add a double check for last modified from the filesystem.

**Comment by LarsDenBakker** [comment] 2019-11-03 18:43
@cristinecula can you try with the latest es-dev-server?

**Comment by cristinecula** [comment] 2019-11-04 07:35
@LarsDenBakker I'll try it right now.

**Comment by cristinecula** [comment] 2019-11-04 08:09
I have tried to replicate the issue, but it does not seem to happen anymore. The load time was not affected by this change.
Thank you very much for resolving this! :clinking_glasses:

**Comment by bennypowers** [comment] 2019-11-04 18:02
Closing as solved. Thank you for the issue. Please tell us if this continues to be a problem.

**Closed by bennypowers** 2019-11-04 18:02 UTC
