### ISSUE TITLE
[es-dev-server] OOM error after a few reloads

### ISSUE THREAD

**Issue by justinfagnani** [open-wc/open-wc#739] opened 2019-08-15 16:44 UTC
I'm using pdf.js via https://github.com/bundled-es-modules/pdfjs-dist which has some very large files, but they're not changing between reloads.

**Comment by LarsDenBakker** [comment] 2019-08-15 20:25
OOM on the server side? Thats not good, I will investigate

**Comment by LarsDenBakker** [comment] 2019-08-16 06:42
I'm not able to reproduce this, are you importing just `@bundled-es-modules/pdfjs-dist` ? Do you have any other flags enabled?

**Comment by justinfagnani** [comment] 2019-08-16 16:04
My command is just `es-dev-server --node-resolve`. Here's my imports and a config setup that causes the worker to load:

```ts
import {LitElement, html, css, property, customElement, PropertyValues} from 'lit-element';
import pdfjs from '@bundled-es-modules/pdfjs-dist';
import viewer from "@bundled-es-modules/pdfjs-dist/web/pdf_viewer";

pdfjs.GlobalWorkerOptions.workerSrc =
    '/node_modules/@bundled-es-modules/pdfjs-dist/build/pdf.worker.min.js';
```

You might have to new the viewer to get the worker to load. Fetching it might simulate that. It only took a few reloads to OOM.

The workaround is: `es-dev-server --node-resolve --babel-exclude=**/@bundled-es-modules/pdfjs-dist/build/*`

**Comment by LarsDenBakker** [comment] 2019-08-17 17:53
I wasn't able to get the worker running, but I'm getting out of memory errors when importing `'@bundled-es-modules/pdfjs-dist/build/pdf.worker.js';` as well.

It runs out of memory during babel compilation when creating source maps, if I turn off source maps in babel it works fine. We might want to turn off source maps, especially for node modules.

With https://github.com/open-wc/open-wc/pull/741 we're no longer using babel for resolving imports, so this that will solve this case as well.

**Comment by LarsDenBakker** [comment] 2019-08-19 18:36
Source maps are quite nice, especially when people use babel to transform typescript etc. so it'd be a shame to turn them off entirely.

After some playing around with this, I opted for disabling source maps for libraries over 500kb. That's an arbitrary number, I based it around when babel starts deoptimizing the output code styles. We can always adjust this number later.

**Comment by justinfagnani** [comment] 2019-08-19 21:09
That sounds fine. Files that large are probably compiled and have their own source map, and possibly the only transform in the server is the specifier rewrites, which won't affect the source map much.

**Closed** 2019-08-20 09:41 UTC
