### ISSUE TITLE
linting types setup error

### ISSUE THREAD

**Issue by hikaruna** [open-wc/open-wc#1042] opened 2019-11-24 20:22 UTC
https://open-wc.org/linting/linting-types.html#setup

```
root@660fc52bb0e8:/todo-app# npm init @open-wc linting-types-jsnpx: 30個のパッケージを4.211秒でインストールしました。
/root/.npm/_npx/1156/lib/node_modules/@open-wc/create/node_modules/command-line-args/dist/index.js:1345
        throw err
        ^

UNKNOWN_VALUE: Unknown value: linting-types-js
    at commandLineArgs (/root/.npm/_npx/1156/lib/node_modules/@open-wc/create/node_modules/command-line-args/dist/index.js:1342:21)
    at Object.<anonymous> (/root/.npm/_npx/1156/lib/node_modules/@open-wc/create/dist/generators/app/index.js:69:48)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/.npm/_npx/1156/lib/node_modules/@open-wc/create/dist/create.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  name: 'UNKNOWN_VALUE',
  value: 'linting-types-js'
}
```

**Comment by LarsDenBakker** [comment] 2020-02-28 21:23
Duplicate of https://github.com/open-wc/open-wc/issues/1056, will keep the other one open since it explains how to fix this.

**Closed by LarsDenBakker** 2020-02-28 21:23 UTC
Labels: bug, docs
