### ISSUE TITLE
Tests fail after generation and minor modification

### ISSUE THREAD

**Issue by Pickra** [open-wc/open-wc#2487] opened 2022-08-16 21:59 UTC
## Expected behavior
The tests should pass and reflect the changes made to the components.

### Workflow
- Generate the repo via `npm init @open-wc`.
- Make a minor change to the generated component, and update it's generated test to match the component change
- Tests pass

## Actual Behavior
The tests failed, didn't reflect the change in the component.

### Workflow
- Generated the repo via `npm init @open-wc`.
- Ran the generated test, it passed
- Changed the `__increment` method of the generated component to increment by `2`
  - from `__increment() { this.counter += 1; }` => `__increment() { this.counter += 2; }`
- Updated the test to accommodate the `__increment` method change
```ts
  it('increases the counter on button click', async () => {
    // counter = 5
    const el = await fixture<OpenWc>(html`<open-wc></open-wc>`);
    el.shadowRoot!.querySelector('button')!.click();
    expect(el.counter).to.equal(7);
  });
```
- ran the test, it failed

I saw the issue about [connectedCallback()](https://github.com/open-wc/open-wc/issues/2275#issuecomment-907507678), didn't think that mattered but tried it anyway; no change

## Additional context
[Test Repo](https://github.com/Pickra/open-wc)

OS: Mac
node : v14.17.0
npm : 6.14.13

"@custom-elements-manifest/analyzer": "^0.4.17",
"@open-wc/scoped-elements": "2.1.2",
"@open-wc/testing": "3.1.6",
"@web/dev-server": "^0.1.28",
"@web/dev-server-storybook": "0.5.1",
"@web/test-runner": "next",
"concurrently": "^5.3.0",
"lit": "2.2.7"
"lit-html": "2.2.6",
"tslib": "^2.3.1",
"typescript": "^4.5.2"

I'm missing something obvious right? Thank you for your time.

**Comment by web-padawan** [comment] 2022-11-17 14:42
Tried this in a fresh project and could not reproduce. After updating the code without changing the test, it fails.

![Screenshot 2022-11-17 at 16 37 34](https://user-images.githubusercontent.com/10589913/202475058-667c27d3-8b00-476e-8283-a02cddc92da2.png)

The project that you provided has incorrect folder structure with `example` folder that causing tests to fail. Closing.

**Closed by web-padawan** 2022-11-17 14:42 UTC
